// packages/frontend/src/lib/components/LivestreamDetails.svelte
<script lang="ts">
  export let livestreamId: number;

  // Mock data - replace with actual API call
  const livestream = {
    id: livestreamId,
    title: 'Livestream Title',
    date: '2023-05-15',
    status: 'Scheduled',
    shareUrl: 'https://example.com/livestream/123',
  };

  function deleteLivestream() {
    if (confirm('Are you sure you want to delete this livestream?')) {
      // Implement delete logic here
      alert('Livestream deleted');
    }
  }
</script>

<div class="card">
  <h2>{livestream.title}</h2>
  <p>Date: {livestream.date}</p>
  <p>Status: {livestream.status}</p>
  <p>Share URL: <a href={livestream.shareUrl}>{livestream.shareUrl}</a></p>
  <div class="button-container">
    <button class="primary-button" on:click={() => alert('Edit livestream')}>
      Edit Livestream
    </button>
    <button class="danger-button" on:click={deleteLivestream}>
      Delete Livestream
    </button>
  </div>
</div>

<style lang="scss">
  @import '../../styles//styles.scss';

 .card {
    @include card;
    background-color: white;
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);

    h2 {
      font-size: 1.5rem;
      font-weight: bold;
      margin-bottom: 1rem;
      color: $text-color;
    }

    p {
      margin-bottom: 0.5rem;
      color: $text-color-secondary;
    }

    a {
      color: $secondary-color;
      text-decoration: none;

      &:hover {
        text-decoration: underline;
      }
    }
  }

  .button-container {
    display: flex;
    justify-content: space-between;
    margin-top: 1rem;
  }

  .primary-button {
    @include button($primary-color, $background-color);
  }

  .danger-button {
    @include button($danger-color, $background-color);
  }
</style>

// packages/frontend/src/lib/components/LivestreamDetails.tsx
const LivestreamDetails = ({
  livestreamId,
}: {
  livestreamId: string | undefined;
}) => {
  // Mock data - replace with actual API call
  const livestream = {
    id: livestreamId,
    title: "Livestream Title",
    date: "2023-05-15",
    status: "Scheduled",
    shareUrl: "https://example.com/livestream/123",
  };

  const deleteLivestream = () => {
    if (window.confirm("Are you sure you want to delete this livestream?")) {
      // Implement delete logic here
      alert("Livestream deleted");
    }
  };

  return (
    <div className="rounded-lg shadow-md">
      <h2 className="text-xl font-bold mb-4 text-primary-white">
        {livestream.title}
      </h2>
      <p className="text-primary-white mb-2">Date: {livestream.date}</p>
      <p className="text-primary-white mb-2">Status: {livestream.status}</p>
      <p className="text-primary-white mb-2">
        Share URL:{" "}
        <a href={livestream.shareUrl} className="text-blue-500 hover:underline">
          {livestream.shareUrl}
        </a>
      </p>
      <div className="flex flex-col gap-4 mt-4">
        <div>
          <button
            className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition"
            onClick={() => alert("Edit livestream")}
          >
            Edit Livestream
          </button>
        </div>
        <div>
          <button
            className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition"
            onClick={deleteLivestream}
          >
            Delete Livestream
          </button>
        </div>
      </div>
    </div>
  );
};

export default LivestreamDetails;
