// packages/frontend/src/lib/components/projectsCard.tsx
import React from 'react';
import { ProjectDetails } from '../../context/types';

const ProjectCard = ({ project }: {project: ProjectDetails}) => {
  return (
    <a
      href={`/dashboard/projects/${project.id}`}
      className="block bg-dark-gray rounded-lg p-6 shadow-md transition-shadow border border-primary-border duration-300 hover:shadow-lg"
    >
      <div>
        <img src={project?.image_url} alt="" className='h-12 w-full' />
      </div>
      <h2 className="text-xl text-primary-white font-semibold mb-2">
        {project.title}
      </h2>
      <p className="text-[#fff6ffd1]">{project.description}</p>
      <div>
        <span className="text-[#fff6ffd1] text-sm">Date Created: 12/06/2024</span>
      </div>
    </a>
  );
};

export default ProjectCard;

// packages/frontend/src/lib/components/projectsCard.svelte
<script lang="ts">
  export let project: { id: number; name: string; description: string };
</script>

<a href="/dashboard/projects/{project.id}" class="card">
  <h2>{project.name}</h2>
  <p>{project.description}</p>
</a>

<style lang="scss">
  .card {
    display: block;
    background-color: white;
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition: box-shadow 0.3s;

    &:hover {
      box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);
    }

    h2 {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    p {
      color: #666;
    }
  }
</style>
