// packages/frontend/src/lib/sidebar.svelte
<script>
	import { page } from '$app/stores';

	export const navItems = [
		{ label: 'Home', value: 'home', route: '/dashboard/home' },
		{ label: 'Projects', value: 'project', route: '/dashboard/projects' },
		{ label: 'Destination', value: 'destination', route: '/dashboard/projects' }
		// { label: 'About', value: 'about', route: '/about' },
		// { label: 'Blog', value: 'blog', route: '/blog' },
		// { label: 'Partners', value: 'partners', route: '/partners' }
	];
</script>

<aside class="sidebar">
	<ul>
		{#each navItems as item}
			<li class={`${$page.url.pathname === item.route ? 'active' : ''}`}>
				<a href={item.route}>{item.label}</a>
			</li>
		{/each}
	</ul>
</aside>

<style lang="scss">
	.sidebar {
		flex-basis: 20%;
		padding: 20px;
		background-color: #1e1e1e;
		margin-top: 72px;
		border-right: 1px solid hsl(155, 6%, 42.5%);

		ul {
			list-style: none;
			padding: 0;
			display: flex;
			flex-direction: column;
			gap: 20px;

			.active {
				background-color: #ffffff;
				a {
					color: #1e1e1e;
				}
			}

			li {
                padding: 10px;
                border-radius: 8px;
				a {
					text-decoration: none;
					color: #ffffff;
					font-family: 'Raleway' 'sans-serif';
				}
			}
		}
	}

	@media (max-width: 650px) {
		.sidebar {
			position: absolute;
			bottom: 0;
            right: 0;
            left: 0;
			margin-top: 10px;
			border-right: none;
			border-top: 1px solid hsl(155, 6%, 42.5%);

			ul {
				display: flex;
				flex-direction: row;
                overflow-x: scroll;
				width: 100%;
				justify-content: space-between;
			}
		}
	}
</style>

// packages/frontend/src/lib/sidebar.tsx
import { useLocation, useNavigate } from "react-router-dom";
import { navItems } from "../utils/navContent";

function Sidebar() {
  const location = useLocation();
  let navigate = useNavigate();

  const isActive = (path: string) => {
    if (path === "/dashboard/projects") {
      return location.pathname.startsWith("/dashboard/projects");
    }
    return location.pathname === path;
  };

  return (
    <aside className="fixed w-[20%] top-0 bottom-0 left-0 right-0 px-5 mt-[57px] pt-8 h-full bg-[#1e1e1e]  border-r-0 border-[hsl(155,6%,42.5%)] md:flex md:flex-col md:gap-5 md:border-r">
      <ul className="list-none p-0 flex flex-col gap-5  md:w-full md:justify-between">
        {navItems.map((item) => (
          <li
            key={item.value}
            className={`${
              isActive(item.route) ? "bg-white text-[#1e1e1e]" : "text-white"
            } p-2 rounded-md no-underline font-raleway cursor-pointer`}
            onClick={() => navigate(item.route)}
          >
            {item.label}
          </li>
        ))}
      </ul>
    </aside>
  );
}

export default Sidebar;
